on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          python3 inline.py
          mkdir -p dist
          cp *.html *.png dist

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: b8079ffa92c97010f2a8d759e24cc782
          projectName: ti84
          directory: dist